services:
  luxonis:
    image: husarion/depthai:humble-2.8.1
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ./rgbd-pcl.yaml:/rgbd-pcl.yaml
    device_cgroup_rules:
      - 'c 189:* rmw'
    command: >
      ros2 launch depthai_ros_driver rgbd_pcl.launch.py
        camera_model:=OAK-D-LITE
        params_file:=/rgbd-pcl.yaml

  rviz:
    image: husarion/rviz2:humble-11.2.6
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./default.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=1
